ctripcorp/x-pipe

- redis/redis-console/src/main/resources/META-INF/dal/jdbc/meta-dal.xml
- redis/redis-console/src/main/resources/static/scripts/controllers/ClusterDcShardUpdateCtl.js
Fix 一个Integration Test 中，由于h2 db 不能兼容bulk insert，自增ID的bug
> Fix the bug that UT will fail due to h2 db

- core/src/main/java/com/ctrip/xpipe/metric/MetricData.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/healthcheck/delay/MetricDelayListener.java
- redis/redis-integration-test/src/test/java/com/ctrip/xpipe/redis/integratedtest/stability/metric/HickwallMetric.java
- services/ctrip-service/src/main/java/com/ctrip/xpipe/service/metric/HickwallMetric.java
- services/ctrip-service/src/test/java/com/ctrip/xpipe/service/metric/HickwallMetricTest.java
> add dc name for hickwall tag

- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/alert/ALERT_TYPE.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/config/ConsoleConfig.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/config/impl/DefaultConsoleConfig.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/DBVariablesCheck.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/DatabaseVariablesCheck.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/VariableChecker.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/checker/AbstractVariableChecker.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/checker/ExitActionChecker.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/checker/UnreachableMajorityTimeoutChecker.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/AllTests.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/DBVariablesCheckTest.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/healthcheck/nonredis/dbvariables/checker/VariablesCheckerTest.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/config/DefaultMetaServerConfig.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/config/MetaServerConfig.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/config/UnitTestServerConfig.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/meta/impl/DefaultDcMetaCache.java
- redis/redis-meta/src/test/java/com/ctrip/xpipe/redis/meta/server/meta/impl/DefaultDcMetaCacheRefreshTest.java
- redis/redis-meta/src/test/java/com/ctrip/xpipe/redis/meta/server/meta/impl/DefaultDcMetaCacheTest.java
- redis/redis-meta/src/test/resources/meta-test.xml
1、wait for a while after primary dc change to load dc meta from console
2、check for db variables group_replication_unreachable_majority_timeout, group_replication_exit_state_action
> support DB MGR mode

- core/src/main/java/com/ctrip/xpipe/command/ConditionalCommand.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/dcchange/DefaultChangePrimaryDcAction.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/dcchange/impl/AbstractNewMasterChooser.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/keeper/DefaultKeeperStateChangeHandler.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/rest/impl/DispatcherMetaServerController.java
- redis/redis-meta/src/main/java/com/ctrip/xpipe/redis/meta/server/spring/MetaServerContextConfig.java
- redis/redis-meta/src/test/java/com/ctrip/xpipe/redis/meta/server/keeper/DefaultKeeperStateChangeHandlerTest.java
1. independent executor
2. check redis role async
3. double check isPrimaryDc before backup-dc keeper adjust
> metaserver migration optmize

- redis/package/redis-keeper-package/src/main/scripts/network/check_time.sh
- redis/package/redis-keeper-package/src/main/scripts/network/start.sh
- redis/package/redis-keeper-package/src/main/scripts/network/stop.sh
- redis/package/redis-keeper-package/src/main/scripts/network/trigger_add_cron.sh
- redis/package/redis-keeper-package/src/main/scripts/network/upload_iplists.sh
- redis/package/redis-keeper-package/src/main/scripts/upload/batch_upload_files.sh
- redis/package/redis-keeper-package/src/main/scripts/upload/upload_files.sh
add check time before isolate network; modify log
> add check time before isolate network; modify log

- redis/package/redis-keeper-package/src/main/scripts/network/check_time.sh
fix network isolation script: adjust system time consistently
> fix network isolation script: adjust system time consistently

- redis/package/redis-keeper-package/src/main/scripts/network/README.md
- redis/package/redis-keeper-package/src/main/scripts/network/analyze_isolate_time.sh
- redis/package/redis-keeper-package/src/main/scripts/network/generate_iplist.sh
- redis/package/redis-keeper-package/src/main/scripts/network/generate_iplist_just_isolate_beacon.sh
- redis/package/redis-keeper-package/src/main/scripts/network/remote_cron/cancel_cron.sh
- redis/package/redis-keeper-package/src/main/scripts/network/remote_cron/isolate_iplist.sh
- redis/package/redis-keeper-package/src/main/scripts/network/remote_cron/recovery_iplist.sh
- redis/package/redis-keeper-package/src/main/scripts/network/start.sh
- redis/package/redis-keeper-package/src/main/scripts/network/stop.sh
modify network isolate script: support isolate beacon only; support recovery network by crontab
> 修改断网脚本：只断beacon，断网恢复改为使用cron定时任务

- redis/package/redis-keeper-package/src/main/config/log4j2-uat.xml
> change uat keeper log size

- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/controller/api/data/RouteApiController.java
修复RouteController bean名称冲突导致无法spring启动问题。
> fix RouteController bean name conflict.

- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/controller/api/data/MetaUpdate.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/service/ShardService.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/service/impl/ClusterServiceImpl.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/service/impl/DefaultCrossMasterDelayService.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/service/impl/DefaultCrossMasterDelayServiceTest.java
- redis/redis-console/src/test/resources/dc-meta-test.xml
1. allow delete cluster only when cluster is empty
2. [bugfix] judge deleted shard as unhealthy shard
> api delete empty cluster

- .github/workflows/build.yml
- pom.xml
> add ci test

- redis/redis-console/src/main/resources/static/views/index/cluster_dc_shards.html
cluster dc shards page add cluster id.
> cluster dc shards page add cluster id.

- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/cache/TimeBoundCache.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/impl/TestMetaCache.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/controller/api/checker/ConsoleCheckerController.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/model/ProxyModel.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/proxy/impl/DefaultProxyChain.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/proxy/impl/DefaultProxyChainAnalyzer.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/proxy/impl/DefaultProxyChainCollector.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/proxy/impl/DefaultTunnelInfo.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/resources/AbstractMetaCache.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/resources/DefaultMetaCache.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/proxy/impl/DefaultProxyChainCollectorTest.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/proxy/impl/DefaultProxyChainTest.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/meta/MetaCache.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/proxy/monitor/SessionTrafficResult.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/proxy/monitor/SocketStatsResult.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/proxy/monitor/TunnelSocketStatsResult.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/proxy/monitor/TunnelStatsResult.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/proxy/monitor/TunnelTrafficResult.java
[cpu] remove refactor using in proxyChainApi && adjust proxyChain collection interval 1s -> 60s
[gc] cache xml format xpipe meta, avoid redundant xml building
> console cpu/gc optimize

- redis/dockerPackage/xpipe-console/sql/xpipedemodbtables.sql
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/controller/api/data/SentinelUpdateController.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/model/SentinelGroupModel.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/sentinel/SentinelBalanceTask.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/sentinel/impl/BackupDcOnlySentinelBalanceTask.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/sentinel/impl/DefaultSentinelBalanceService.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/service/SentinelGroupService.java
- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/service/impl/SentinelGroupServiceImpl.java
- redis/redis-console/src/main/resources/META-INF/dal/jdbc/meta-codegen.xml
- redis/redis-console/src/main/resources/sql/h2/xpipedemodbtables.sql
- redis/redis-console/src/main/resources/sql/mysql/xpipedemodbtables.sql
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/sentinel/impl/DefaultSentinelBalanceServiceTest.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/service/impl/DcClusterShardServiceImplTest.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/service/impl/SentinelGroupServiceTest.java
- redis/redis-console/src/test/resources/sentinel-balance-test.sql
1. active=0的sentinel group不会在rebalance或者添加分片时被选中
2. active=0的sentinel group仍然像其他正常sentinel group一样工作
> add active to sentinel group

- core/pom.xml
- pom.xml
- redis/package/pom.xml
- redis/package/redis-console-package/pom.xml
- redis/package/redis-keeper-package/pom.xml
- redis/package/redis-metaserver-package/pom.xml
- redis/package/redis-proxy-package/pom.xml
- redis/pom.xml
- redis/redis-checker/pom.xml
- redis/redis-console/pom.xml
- redis/redis-core/pom.xml
- redis/redis-integration-test/pom.xml
- redis/redis-keeper/pom.xml
- redis/redis-meta/pom.xml
- redis/redis-proxy-client/pom.xml
- redis/redis-proxy-client/src/main/java/com/ctrip/framework/xpipe/redis/utils/ProxyUtil.java
- redis/redis-proxy-client/src/test/java/com/ctrip/framework/xpipe/redis/utils/ProxyUtilTest.java
- redis/redis-proxy/pom.xml
- services/ctrip-integration-test/pom.xml
- services/ctrip-service/pom.xml
- services/local-service/pom.xml
- services/pom.xml
fixbug: possible npe 
proxyUtil.getProxyConnectProtocol while proxyUtil.registerProxy
> fixbug: register cause npe

- redis/redis-console/src/main/java/com/ctrip/xpipe/redis/console/proxy/impl/AbstractTunnelSocketStatsAnalyzer.java
- redis/redis-console/src/test/java/com/ctrip/xpipe/redis/console/proxy/impl/DefaultTunnelSocketStatsAnalyzerManagerTest.java
> set empty tag while tag can not get

- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/sentinel/collector/command/ResetSentinels.java
> Revert "reset sentinels async"

- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/sentinel/collector/CurrentDcSentinelHelloCollector.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/sentinel/collector/DefaultSentinelHelloCollector.java
> Revert "fix getRedisOfDcClusterShard in sentinel check"

- pom.xml
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/sentinel/collector/DefaultSentinelHelloCollector.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/sentinel/collector/command/ResetSentinels.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/sentinel/collector/command/SentinelHelloCollectContext.java
- redis/redis-checker/src/test/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/sentinel/collector/command/ResetSentinelsTest.java
> Revert "optimized sentinel reset"

- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/interaction/processor/route/DefaultRouteHealthEventProcessor.java
- redis/redis-checker/src/test/java/com/ctrip/xpipe/redis/checker/healthcheck/actions/interaction/processor/route/DefaultRouteHealthEventProcessorTest.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/protocal/cmd/InfoCommand.java
- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/protocal/cmd/InfoResultExtractor.java
> Revert "fix rdb size miscalculated"

- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/alert/ALERT_TYPE.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/alert/message/DelayAlertRecoverySubscriber.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/alert/message/subscriber/AbstractAlertEntitySubscriber.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/alert/message/subscriber/AlertEntityDelaySubscriber.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/alert/message/subscriber/AlertRecoverySubscriber.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/alert/message/subscriber/RepeatAlertEntitySubscriber.java
- redis/redis-checker/src/test/java/com/ctrip/xpipe/redis/checker/alert/message/subscriber/AlertEntityDelaySubscriberTest.java
针对快速恢复的告警，等待5分钟 看看是否能恢复。不恢复再告警
> Wait a minute to send an alarm. Some alarms recover quickly.

- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/meta/ClusterMetaVisitor.java
- redis/redis-checker/src/main/java/com/ctrip/xpipe/redis/checker/healthcheck/meta/ShardMetaVisitor.java
- redis/redis-checker/src/test/java/com/ctrip/xpipe/redis/checker/healthcheck/meta/DefaultDcMetaChangeManagerTest.java
> Revert "remove cluster meta change filter"

- redis/redis-core/src/main/java/com/ctrip/xpipe/redis/core/redis/rdb/parser/RdbZSet2Parser.java
> repair direct memory leak

- redis/redis-keeper/src/main/java/com/ctrip/xpipe/redis/keeper/config/DefaultKeeperConfig.java
- redis/redis-keeper/src/main/java/com/ctrip/xpipe/redis/keeper/config/KeeperConfig.java
- redis/redis-keeper/src/main/java/com/ctrip/xpipe/redis/keeper/config/TestKeeperConfig.java
- redis/redis-keeper/src/main/java/com/ctrip/xpipe/redis/keeper/container/KeeperContainerService.java
- redis/redis-keeper/src/main/java/com/ctrip/xpipe/redis/keeper/impl/DefaultRedisMasterReplication.java
> support skip ror rdb

- services/ctrip-service/src/main/java/com/ctrip/xpipe/service/metric/HickwallMetric.java
- services/ctrip-service/src/main/java/com/ctrip/xpipe/service/metric/InfluxDbClient.java
- services/ctrip-service/src/test/java/com/ctrip/xpipe/service/metric/HickwallMetricTest.java
如果连不上hickwall会启动失败，属于强依赖了，这里改一下
> Don't rely too heavily on hickwall
